services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  weather-service:
    build: ./weather-service
    container_name: weather-service
    environment:
      - OPENWEATHER_API_KEY=e4e92e7da19bc77f1df2ba9e6db5ec3d
    ports:
      - "4001:4001"

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - weather-service
    ports:
      - "4000:4000"

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    stdin_open: true
    depends_on:
      - gateway

  analytics-service:
    build: ./analytics-service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/weather
    depends_on:
      - mongo
